;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="AI.Status.Chase",DevComment="Персонаж находится в погоне (актуально как для Противника, так и для Подопечного)")
GameplayTagList=(Tag="AI.Status.Exploration",DevComment="Персонаж находится в режиме исследования локации")
GameplayTagList=(Tag="AI.Status.Panic",DevComment="Персонаж в состоянии паники (из механики стресса)")
GameplayTagList=(Tag="AI.Status.Reaction",DevComment="Персонаж реагирует на внешний стимул (шум, движение)")
GameplayTagList=(Tag="AI.Status.Tension",DevComment="Персонаж находится в состоянии повышенной готовности")
GameplayTagList=(Tag="Door.Status.Closed",DevComment="Дверь закрыта")
GameplayTagList=(Tag="Door.Status.Locked",DevComment="Дверь заблокирована")
GameplayTagList=(Tag="Door.Status.Open",DevComment="Дверь открыта")
GameplayTagList=(Tag="Door.Status.Unknown",DevComment="Базовое значение. Статус двери неизвестен ИИ")
GameplayTagList=(Tag="Session.Status.Basic",DevComment="Базовый этап. Основной игровой процесс до набора 6 очков")
GameplayTagList=(Tag="Session.Status.Final",DevComment="Финальный этап. Доступен побег с локации. Наступает после получения 6 очков")
GameplayTagList=(Tag="Session.Status.Loading",DevComment="Этап загрузки. Просчитываются параметры уровня, спавнятся печати, все классы проходят первоначальную настройку")
GameplayTagList=(Tag="Stat.Ward.SealProgressSpeed",DevComment="Количество очков, начисляемых в Печать за секунду взаимодействия")

