;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Stat",DevComment="")
+GameplayTagList=(Tag="Stat.InteractionSpeed",DevComment="")
+GameplayTagList=(Tag="Stat.MoveSpeed",DevComment="")
+GameplayTagList=(Tag="Stat.ReactionTime",DevComment="")
+GameplayTagList=(Tag="Stat.Stress.Coefficient.Aggressive",DevComment="")
+GameplayTagList=(Tag="Stat.Stress.Coefficient.ChaseBegin",DevComment="")
+GameplayTagList=(Tag="Stat.Stress.Coefficient.Darkness",DevComment="")
+GameplayTagList=(Tag="Stat.Stress.Coefficient.EnemyNotice",DevComment="")
+GameplayTagList=(Tag="Stat.Stress.Coefficient.Noise",DevComment="")
+GameplayTagList=(Tag="Stat.Stress.Coefficient.Permanent",DevComment="")
+GameplayTagList=(Tag="Stat.Stress.Coefficient.Supernatural",DevComment="")
+GameplayTagList=(Tag="Stat.Stress.Coefficient.Temporary",DevComment="")
+GameplayTagList=(Tag="Stat.Stress.Coefficient.Trap",DevComment="")
+GameplayTagList=(Tag="Stat.Stress.Permanent",DevComment="")
+GameplayTagList=(Tag="Stat.Stress.Temporary",DevComment="")
+GameplayTagList=(Tag="Stat.Stress.Threshold.Calm",DevComment="")
+GameplayTagList=(Tag="Stat.Stress.Threshold.Mobilization",DevComment="")
+GameplayTagList=(Tag="Stat.Stress.Threshold.Panic",DevComment="")
+GameplayTagList=(Tag="State.Stress.Calm",DevComment="")
+GameplayTagList=(Tag="State.Stress.Mobilization",DevComment="")
+GameplayTagList=(Tag="State.Stress.OnTheEdge",DevComment="")
+GameplayTagList=(Tag="State.Stress.Panic",DevComment="")

