;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Seal",DevComment="")
+GameplayTagList=(Tag="Seal.Status",DevComment="")
+GameplayTagList=(Tag="Seal.Status.Blocked",DevComment="Печать заблокирована противником. Временное состояние, взаимодействие невозможно")
+GameplayTagList=(Tag="Seal.Status.Completed",DevComment="Печать распечатана. Конечное состояние, награда выдана")
+GameplayTagList=(Tag="Seal.Status.Hidden",DevComment="Печать скрыта. Базовое состояние, недоступна для взаимодействия")
+GameplayTagList=(Tag="Seal.Status.Revealed",DevComment="Печать раскрыта. Доступна для распечатывания")
+GameplayTagList=(Tag="Stat",DevComment="")
+GameplayTagList=(Tag="Stat.InteractionSpeed",DevComment="")
+GameplayTagList=(Tag="Stat.MoveSpeed",DevComment="")
+GameplayTagList=(Tag="Stat.ReactionTime",DevComment="")
+GameplayTagList=(Tag="Stat.Seal",DevComment="Корневой тег для всех числовых характеристик печати")
+GameplayTagList=(Tag="Stat.Seal.BlockDuration",DevComment="Время блокировки печати (в секундах) после взаимодействия с противником")
+GameplayTagList=(Tag="Stat.Seal.RequiredPoints",DevComment="Количество очков, необходимое для распечатывания печати")
+GameplayTagList=(Tag="Stat.Seal.RevealDuration",DevComment="Время (в секундах), необходимое для раскрытия печати (удержание MainHoldAction)")
+GameplayTagList=(Tag="Stat.Stress.Coefficient.Aggressive",DevComment="")
+GameplayTagList=(Tag="Stat.Stress.Coefficient.ChaseBegin",DevComment="")
+GameplayTagList=(Tag="Stat.Stress.Coefficient.Darkness",DevComment="")
+GameplayTagList=(Tag="Stat.Stress.Coefficient.EnemyNotice",DevComment="")
+GameplayTagList=(Tag="Stat.Stress.Coefficient.Noise",DevComment="")
+GameplayTagList=(Tag="Stat.Stress.Coefficient.Permanent",DevComment="")
+GameplayTagList=(Tag="Stat.Stress.Coefficient.Supernatural",DevComment="")
+GameplayTagList=(Tag="Stat.Stress.Coefficient.Temporary",DevComment="")
+GameplayTagList=(Tag="Stat.Stress.Coefficient.Trap",DevComment="")
+GameplayTagList=(Tag="Stat.Stress.Permanent",DevComment="")
+GameplayTagList=(Tag="Stat.Stress.Temporary",DevComment="")
+GameplayTagList=(Tag="Stat.Stress.Threshold.Calm",DevComment="")
+GameplayTagList=(Tag="Stat.Stress.Threshold.Mobilization",DevComment="")
+GameplayTagList=(Tag="Stat.Stress.Threshold.Panic",DevComment="")
+GameplayTagList=(Tag="Stat.Ward.SealProgressSpeed",DevComment="Скорость накопления очков для распечатывания печати (очков/сек)")
+GameplayTagList=(Tag="State.Stress.Calm",DevComment="")
+GameplayTagList=(Tag="State.Stress.Mobilization",DevComment="")
+GameplayTagList=(Tag="State.Stress.OnTheEdge",DevComment="")
+GameplayTagList=(Tag="State.Stress.Panic",DevComment="")

